### ISSUE TITLE
Failed to patch Reddit V2024.18.0

### ISSUE THREAD

**Issue by donw7eed** [anddea/revanced-patches#407] opened 2024-04-30 09:43 UTC
### Type

Error while patching

### Tools used

Revancify

### Application

Reddit V2024.18.0

### Bug description

Failed to patch Reddit 

### Error logs

```shell
INFO: Loading patches INFO: Decoding app manifest INFO: Custom branding name Reddit excluded INFO: Change package name excluded INFO: Hide toolbar button excluded INFO: Setting patch options INFO: Merging integrations INFO: Deleting existing resource cache directory INFO: Decoding resources INFO: Executing patches INFO: Disable screenshot popup succeeded INFO: Hide ads succeeded INFO: Hide navigation buttons succeeded INFO: Hide recently visited shelf succeeded INFO: Open links directly succeeded INFO: Open links externally succeeded INFO: Premium icon succeeded INFO: Remove subreddit dialog succeeded INFO: Sanitize sharing links succeeded INFO: Settings succeeded INFO: Compiling patched dex files INFO: Compiled classes.dex INFO: Compiled classes2.dex INFO: Compiled classes3.dex INFO: Compiled classes4.dex INFO: Compiled classes5.dex INFO: Compiled classes6.dex INFO: Compiled classes7.dex INFO: Compiled classes8.dex INFO: Compiled classes9.dex INFO: Compiled classes10.dex INFO: Compiled classes11.dex INFO: Compiled classes12.dex INFO: Compiling modified resources WARNING: /data/data/com.termux/files/home/revancify-data/apps/Reddit-2024.18.0/base-RVX-anddea-resource-cache/res/values/styles.xml:2661: error: expected enum but got (raw string) 0. WARNING: /data/data/com.termux/files/home/revancify-data/apps/Reddit-2024.18.0/base-RVX-anddea-resource-cache/res/values/styles.xml:3268: error: expected enum but got (raw string) 1. WARNING: /data/data/com.termux/files/home/revancify-data/apps/Reddit-2024.18.0/base-RVX-anddea-resource-cache/res/values/styles.xml:3271: error: expected enum but got (raw string) 1. WARNING: /data/data/com.termux/files/home/revancify-data/apps/Reddit-2024.18.0/base-RVX-anddea-resource-cache/res/values/styles.xml:3303: error: expected enum but got (raw string) 1. WARNING: error: failed linking references. brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [./aapt2, link, -o, /data/data/com.termux/files/home/revancify-data/apps/Reddit-2024.18.0/base-RVX-anddea-resource-cache/aapt_temp_file, --package-id, 127, --min-sdk-version, 26, --target-sdk-version, 34, --version-code, 1577901, --version-name, 2024.18.0, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/data/com.termux/files/usr/tmp/APKTOOL2249802270257696285.tmp, -0, arsc, -I, /data/data/com.termux/files/home/revancify-data/apps/Reddit-2024.18.0/base-RVX-anddea-resource-cache/1.apk, --manifest, /data/data/com.termux/files/home/revancify-data/apps/Reddit-2024.18.0/base-RVX-anddea-resource-cache/AndroidManifest.xml, /data/data/com.termux/files/home/revancify-data/apps/Reddit-2024.18.0/base-RVX-anddea-resource-cache/build/resources.zip] 	at brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:246) 	at brut.androlib.AaptInvoker.invokeAapt(AaptInvoker.java:391) 	at app.revanced.patcher.data.ResourceContext.get(ResourceContext.kt:128) 	at app.revanced.patcher.Patcher.get(Patcher.kt:265) 	at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:313) 	at picocli.CommandLine.executeUserObject(CommandLine.java:2026) 	at picocli.CommandLine.access$1500(CommandLine.java:148) 	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461) 	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453) 	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415) 	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273) 	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417) 	at picocli.CommandLine.execute(CommandLine.java:2170) 	at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:12) Caused by: brut.common.BrutException: could not exec (exit code = 1): [./aapt2, link, -o, /data/data/com.termux/files/home/revancify-data/apps/Reddit-2024.18.0/base-RVX-anddea-resource-cache/aapt_temp_file, --package-id, 127, --min-sdk-version, 26, --target-sdk-version, 34, --version-code, 1577901, --version-name, 2024.18.0, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/data/com.termux/files/usr/tmp/APKTOOL2249802270257696285.tmp, -0, arsc, -I, /data/data/com.termux/files/home/revancify-data/apps/Reddit-2024.18.0/base-RVX-anddea-resource-cache/1.apk, --manifest, /data/data/com.termux/files/home/revancify-data/apps/Reddit-2024.18.0/base-RVX-anddea-resource-cache/AndroidManifest.xml, /data/data/com.termux/files/home/revancify-data/apps/Reddit-2024.18.0/base-RVX-anddea-resource-cache/build/resources.zip] 	at brut.util.OS.exec(OS.java:104) 	at brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:242) 	... 13 more Rooted: false Arch: arm64-v8a App: Reddit v2024.18.0 CLI: inotia00-cli-v4.4.1.jar Patches: anddea-patches-v2.225.0-dev.1.jar Integrations: anddea-integrations-v0.152.0-dev.1.apk Patches argument: -i Disable screenshot popup -i Hide ads -i Hide navigation buttons -i Hide recently visited shelf -i Open links directly -i Open links externally -i Premium icon -i Remove subreddit dialog -i Sanitize sharing links -i Settings
```

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment] 2024-04-30 10:23
Duplicate of #401. Continue there.

**Closed by anddea** 2024-04-30 10:23 UTC
Labels: Bug report
