### ISSUE TITLE
bug:(YTM) - Replace Cast button failed in supported version

### ISSUE THREAD

**Issue by Vipin2003** [anddea/revanced-patches#568] opened 2024-06-01 18:02 UTC
### Type

Error while patching

### Tools used

rvx-builder

### Application

YTM - Supported

### Bug description

"Replace Cast button" patch get failed even it is shown to be supported with the supported version.

### Error logs

```shell
[builder] INFO: Loading patches
[builder] INFO: Decoding app manifest
[builder] INFO: Excluding Custom branding name YouTube Music
[builder] INFO: Excluding Custom package name INFO: Setting patch options
[builder] INFO: Merging integrations
[builder] INFO: Deleting existing temporary files directory
[builder] INFO: Decoding resources
[builder] INFO: Executing patches
[builder] INFO: Amoled succeeded
[builder] INFO: Bitrate default value succeeded
[builder] INFO: Certificate spoof succeeded
[builder] INFO: Change start page succeeded
[builder] INFO: Custom branding icon YouTube Music succeeded
[builder] INFO: Disable auto captions succeeded
[builder] INFO: Disable dislike redirection succeeded
[builder] INFO: Enable OPUS codec succeeded
[builder] INFO: Enable debug logging succeeded
[builder] INFO: Enable landscape mode succeeded
[builder] INFO: Enable minimized playback succeeded
[builder] INFO: Flyout menu components succeeded
[builder] INFO: GmsCore support succeeded
[builder] INFO: Hide account components succeeded
[builder] INFO: Hide action bar components succeeded
[builder] INFO: Hide ads succeeded
[builder] INFO: Hide double tap overlay filter succeeded
[builder] INFO: Hide layout components succeeded
[builder] INFO: Hide overlay filter succeeded
[builder] INFO: Hide player overlay filter succeeded
[builder] INFO: Navigation bar components succeeded
[builder] INFO: Player components succeeded
[builder] INFO: Remove viewer discretion dialog succeeded
[builder] SEVERE: Replace Cast button failed: app.revanced.patcher.patch.PatchException: 'Replace Cast button' depends on 'PlayerResponsePatch' that raised an exception: app.revanced.patcher.patch.PatchException: Failed to resolve PlaybackStartDescriptorFingerprint at app.revanced.util.BytecodeUtilsKt.getException(BytecodeUtils.kt:43) at app.revanced.util.BytecodeUtilsKt.resultOrThrow(BytecodeUtils.kt:35) at app.revanced.patches.music.utils.playerresponse.PlayerResponsePatch.execute(PlayerResponsePatch.kt:40) at app.revanced.patches.music.utils.playerresponse.PlayerResponsePatch.execute(PlayerResponsePatch.kt:10) at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:173) at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:155) at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:205) at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt) at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt) at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:57) at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:226) at app.revanced.cli.command.PatchCommand$run$4$1$1.invokeSuspend(PatchCommand.kt:315) at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104) at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:277) at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:95) at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:69) at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source) at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:48) at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source) at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:314) at picocli.CommandLine.executeUserObject(CommandLine.java:2026) at picocli.CommandLine.access$1500(CommandLine.java:148) at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461) at picocli.CommandLine$RunLast.handle(CommandLine.java:2453) at picocli.CommandLine$RunLast.handle(CommandLine.java:2415) at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273) at picocli.CommandLine$RunLast.execute(CommandLine.java:2417) at picocli.CommandLine.execute(CommandLine.java:2170) at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:12) at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:160) at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:205) at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt) at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt) at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:57) at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:226) at app.revanced.cli.command.PatchCommand$run$4$1$1.invokeSuspend(PatchCommand.kt:315) at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104) at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:277) at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:95) at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:69) at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source) at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:48) at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source) at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:314) at picocli.CommandLine.executeUserObject(CommandLine.java:2026) at picocli.CommandLine.access$1500(CommandLine.java:148) at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461) at picocli.CommandLine$RunLast.handle(CommandLine.java:2453) at picocli.CommandLine$RunLast.handle(CommandLine.java:2415) at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273) at picocli.CommandLine$RunLast.execute(CommandLine.java:2417) at picocli.CommandLine.execute(CommandLine.java:2170) at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:12)
[builder] INFO: Restore old style library shelf succeeded
[builder] INFO: Return YouTube Dislike succeeded
[builder] INFO: Sanitize sharing links succeeded
[builder] INFO: SponsorBlock succeeded
[builder] INFO: Spoof app version succeeded
[builder] INFO: Translations succeeded
[builder] INFO: Video playback succeeded
[builder] INFO: Visual preferences icons succeeded
[builder] INFO: Settings succeeded
[builder] INFO: Compiling patched dex files
[builder] INFO: Compiled classes.dex
[builder] INFO: Compiled classes2.dex
[builder] INFO: Compiled classes3.dex
[builder] INFO: Compiled classes4.dex
[builder] INFO: Compiled classes5.dex
[builder] INFO: Compiled classes6.dex
[builder] INFO: Compiled classes7.dex
[builder] INFO: Compiled classes8.dex
[builder] INFO: Compiling modified resources
[builder] INFO: Ripping selected native libs
[builder] INFO: Aligning APK
[builder] INFO: Signing APK
[builder] INFO: Saved to /data/data/com.termux/files/home/rvx-builder/revanced/revanced.apk INFO: Purging temporary files
[builder] INFO: Purged resource cache directory
[builder] Copied files over to /storage/emulated/0/!
[builder] Please install ReVanced, its located in /storage/emulated/0/ReVanced-YouTubeMusic-v7.03.51-arm64-v8a-cli_v4.6.1-patches_v2.226.0-dev.4.apk
```

### Device Environment

A14

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by AbakNacchan** [comment] 2024-06-01 18:33
Same here.

```
SEVERE: Replace Cast button failed:
app.revanced.patcher.patch.PatchException: 'Replace Cast button' depends on 'PlayerResponsePatch' that raised an exception:
app.revanced.patcher.patch.PatchException: Failed to resolve PlaybackStartDescriptorFingerprint
	at app.revanced.util.BytecodeUtilsKt.getException(BytecodeUtils.kt:43)
	at app.revanced.util.BytecodeUtilsKt.resultOrThrow(BytecodeUtils.kt:35)
	at app.revanced.patches.music.utils.playerresponse.PlayerResponsePatch.execute(PlayerResponsePatch.kt:40)
	at app.revanced.patches.music.utils.playerresponse.PlayerResponsePatch.execute(PlayerResponsePatch.kt:10)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:173)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:155)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:205)
	at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
	at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:57)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:226)
	at app.revanced.cli.command.PatchCommand$run$4$1$1.invokeSuspend(PatchCommand.kt:315)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:[104](https://github.com/AbakNacchan/RV-X/actions/runs/9332363352/job/25688111690#step:6:105))
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:277)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:95)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:69)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:48)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:314)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:12)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:160)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:205)
	at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
	at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:57)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:226)
	at app.revanced.cli.command.PatchCommand$run$4$1$1.invokeSuspend(PatchCommand.kt:315)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:277)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:95)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:69)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:48)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:314)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:12)
```

**Comment by anddea** [comment] 2024-06-01 20:19
Duplicate of https://github.com/anddea/revanced-patches/issues/563

**Closed by anddea** 2024-06-01 20:19 UTC
Labels: Bug report

**Comment by AbakNacchan** [comment] 2024-06-01 20:31
@anddea it's not present on v2.226.0-dev.2.

**Comment by anddea** [comment] 2024-06-01 20:42
What do you mean, this patch will be removed in new releases, don't know when though.

**Comment by anddea** [comment] 2024-06-01 21:15
The error is shown for the latest YTM I guess. Probably you still can patch older versions with no errors.

**Comment by innit86** [comment] 2024-06-03 13:22
> The error is shown for the latest YTM I guess. Probably you still can patch older versions with no errors.

Yep. 7.02.51, 7.02.52 patches with no error but 7.03.51+ fails.
