### ISSUE TITLE
bug: lag while playing shorts

### ISSUE THREAD

**Issue by soyDESKTOP68A2MRFT** [anddea/revanced-patches#182] opened 2024-03-27 17:11 UTC
### Type

Error at runtime

### Tools used

RVX Manager

### Application

Youtube 19.11.43

### Bug description

While playing shorts i notice sorta lag in some shorts, the shorts play very slowly and laggy, it only happen on one or two shorts before going back to normal

### Error logs

```shell
Idk, i don't know how to catch logs from the app itself
```

### Solution

As far as i know there is no solution

### Device Environment

Android 12, one ui 5.1

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment] 2024-03-27 17:31
1. Is it fine in stock YouTube client?
2. Do you face this issue if you exclude `shorts overlay buttons` patch?
3. Or exclude `hide shorts components`?
4. Or `disable shorts on startup`?

I can't reproduce your issue, so you have to try test those options above and let me know.

**Comment by anddea** [comment] 2024-03-28 11:29
Duplicate of https://github.com/anddea/revanced-patches/issues/75

**Closed by anddea** 2024-03-28 11:29 UTC
Labels: Bug report
