### ISSUE TITLE
bug(YouTube): `Hide seek message` doesn't work in newer YouTube versions

### ISSUE THREAD

**Issue by Kuddus73** [anddea/revanced-patches#48] opened 2024-03-15 02:52 UTC
### Type

Error while patching

### Tools used

RVX Manager

### Application

YouTube v19.09.37
Patches v2.221.0.2

### Bug description

https://github.com/anddea/revanced-patches/assets/127908708/f7f7c483-8449-4377-9e92-1df7b9598380

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment] 2024-03-15 07:20
I can't reproduce it, it works for me on the same YouTube version and Patches.

**Comment by Kuddus73** [comment] 2024-03-16 14:22
@anddea on YouTube v19.05.36 with Patches v2.221.0.3 the bug doesn't happen:

https://github.com/anddea/revanced-patches/assets/127908708/e57bd8ab-3c29-469e-8838-9a1680fc84cf

But on YouTube v19.09.38 with again Patches v2.221.0.3 the bug happens:

https://github.com/anddea/revanced-patches/assets/127908708/de01e2a8-e725-4335-9a8b-4bc50374b58a

**Comment by anddea** [comment] 2024-03-27 21:25
Still can't reproduce it. Do you still face this issue?

**Comment by Kuddus73** [comment] 2024-03-28 05:28
> Still can't reproduce it. Do you still face this issue?

Yes, this is on YouTube v19.09.38 with Patches v2.223.0.dev.13:

https://github.com/anddea/revanced-patches/assets/127908708/74327bb0-ece8-482a-960d-e70fdee94cef

**To reproduce the bug, don't update the YouTube app from YouTube v19.05.36 where the bug is not present.
Try to do a clean installation of YouTube v19.09.38.**

**Comment by anddea** [comment] 2024-03-29 19:21
I tried clean install as well, still can't reproduce it, maybe it's some kind of a new feature flag by Google. Or maybe some other patches interfering. But I guess you face this issue with default settings and default patches?

**Comment by Kuddus73** [comment] 2024-03-30 15:54
> Or maybe some other patches interfering.

I used the same settings and included the same patches with both versions: on YouTube v19.05.36 the bug doesn't happen, but on newer versions like YouTube v19.09.38 it does.

> But I guess you face this issue with default settings and default patches?

Not sure what you mean by default but here are my settings and patches:
[Settings.txt](https://github.com/anddea/revanced-patches/files/14812532/Settings.txt)
[Patches.json](https://github.com/anddea/revanced-patches/files/14812533/Patches.json)

**Comment by Francesco146** [comment] 2024-05-02 19:17
@Kuddus73 can you test this with the latest dev patch and on YouTube v19.16.38?

**Comment by Francesco146** [comment] 2024-05-10 11:56
fixed in RVX

**Closed** 2024-05-10 15:41 UTC
