### ISSUE TITLE
bug: Can't hide some components in account menu.

### ISSUE THREAD

**Issue by joelmzj** [anddea/revanced-patches#248] opened 2024-04-02 00:59 UTC
### Type

Cosmetic

### Tools used

Revancify

### Application

YouTube v19.11.38
patches v2.223.0
integrations v0.150.0

### Bug description

Can't hide "Get YouTube Premium" and buttons below profile name.

I realized that, if made clean installation, those entries are hidden, but, when importing my configuration file, those come back.

I've included in the correct Account menu filter in "General".

![photo_2024-04-01_18-52-31](https://github.com/anddea/revanced-patches/assets/79762041/8e1c20b8-0526-468f-bfcd-8d649c03c63c)
![photo_2024-04-01_18-52-37](https://github.com/anddea/revanced-patches/assets/79762041/ff2547c8-cea5-4e7b-84ac-d2cbce76497f)

### Device Environment

Tested on different devices with different Android versions.

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by malaguer** [comment] 2024-04-02 07:28
Add "Obtener YouTube Premium" to the filters. I mean in your own language and with the same case characters.

I use the Spanish version too. And it's working for me.

**Comment by anddea** [comment] 2024-04-02 18:32
Buttons below profile name are not hidden by this option. 

Although, it's a weird behavior for YouTube premium that should be hidden but for some it is not. 

When you clean install, it shows old interface then after some time it loads new one, more buttons appear, so that's why they was hidden for you and after restarting the app new elements came. So probably, it's not because you inproted settings but because restarted the app.

**Comment by Francesco146** [comment] 2024-05-02 19:21
consider closing this as it's solved

**Comment by anddea** [comment] 2024-05-02 19:39
It's still not hiding "Obtener YouTube Premium".

**Comment by Francesco146** [comment] 2024-05-02 19:53
> It's still not hiding "Obtener YouTube Premium".

just that language? quite impressive

**Comment by anddea** [comment] 2024-05-02 20:06
> just that language? 

Yep, don't know any other cases.

**Comment by Francesco146** [comment] 2024-05-10 12:06
> Yep, don't know any other cases.

this is occurring even in RVX

**Comment by Francesco146** [comment] 2024-06-11 18:51
yt changed the text, should be working now. test it and close this issue if necessary

**Comment by anddea** [comment] 2024-06-11 20:41
I cannot reproduce this issue for now but if you still have this issue reopen in inotia's repo.

**Closed by anddea** 2024-06-11 20:41 UTC
Labels: Bug report
