### ISSUE TITLE
Search bar

### ISSUE THREAD

**Issue by myselfzoro** [anddea/revanced-patches#445] opened 2024-05-10 06:34 UTC
### Application

YouTube

### Feature description

Search bar for revanced extended settings right now people have to post query regarding any particular setting they know it exist but can't find it, it can simply be found if there is a search bar inside ReVanced Extended settings also if possible at a shortcut to ReVanced Extended settings directly to below profile in library page

### Motivation

It will reduce around 20-30% of people queries easily if they can just search where it is rather than depending on community to guide them for small settings location

(Thanks for the work you have been doing and for the future) 

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment] 2024-05-10 08:35
Duplicate of https://github.com/anddea/revanced-patches/issues/68

You can reopen this issue in inotia00 repo.

**Closed by anddea** 2024-05-10 08:35 UTC
Labels: Feature request

**Comment by myselfzoro** [comment] 2024-05-10 09:14
I already did, will do again if you say so
