### ISSUE TITLE
bug(YouTube - Shorts): `Hide Animated Button Background` not working

### ISSUE THREAD

**Issue by andylee516** [anddea/revanced-patches#653] opened 2024-06-26 14:53 UTC
### Type

Error at runtime

### Tools used

Revancify

### Application

youtube version 19.16.39 and higher

### Bug description

hide animated button background, which is the dark circle background form in shorts(click to pause) does not work in latest patch 2.226.0

### Device Environment

android 14

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Francesco146** [comment] 2024-06-26 16:43
can you reproduce it in RVX?

**Comment by Francesco146** [comment] 2024-06-26 16:50
i can't reproduce this in RVX

**Comment by zerozero0022** [comment] 2024-06-26 18:42
'Hide Play & Pause button background in Shorts player' switch will be released in the next RVX version.

**Comment by Francesco146** [comment] 2024-06-26 18:57
we already had those, It seems that when the stable version was released, the files were deleted

**Comment by MondayNitro** [comment] 2024-06-29 07:01
> we already had those, It seems that when the stable version was released, the files were deleted

inotia fixed this in his recent releases

**Comment by Francesco146** [comment] 2024-06-29 08:35
yes, i need to merge his latest changes and then i'll close this

**Closed** 2024-07-01 16:44 UTC
Labels: Bug report
