### ISSUE TITLE
bug: Infinite Loading Issue in videos and shorts

### ISSUE THREAD

**Issue by TheLegendaryPhoenix08** [anddea/revanced-patches#423] opened 2024-05-04 02:31 UTC
### Type

Error while patching

### Tools used

RVX Manager

### Application

Latest patches

### Bug description

Videos and shorts loading infinitely after oalying for 2-3 seconds.

### Error logs

```shell
.
```

### Solution

IDK

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Fred6388** [comment] 2024-05-04 02:36
I have the same issue, I tried patching with rvx and Revancify on all supported versions and I have the same result... 😔

**Comment by Android-PowerUser** [comment] 2024-05-04 07:29
Turn off SafetyNet and log in to your Google account.

**Comment by odkate** [comment] 2024-05-04 07:46
> shorts loading infinitely

On versions with microG, there is no loading wheel in the Shorts

It turns out that this is a issue in GmsCore, not in patches

**Comment by odkate** [comment] 2024-05-04 07:48
> and log

For some reason, I don't have one of these

**Comment by Android-PowerUser** [comment] 2024-05-04 07:56
How come the error occurs now? With NewPipe you can still use YouTube without sign in.

**Comment by odkate** [comment] 2024-05-04 08:08
> Shorts

https://github.com/anddea/revanced-patches/issues/418#issuecomment-2094072150
🤔

**Comment by anddea** [comment] 2024-05-04 08:41
I think it's duplicate of https://github.com/anddea/revanced-patches/issues/418. To make it easier to track, continue there.

**Closed** 2024-05-04 08:41 UTC
Labels: Bug report
