### ISSUE TITLE
bug: Turn on `Append information type` crashed the app

### ISSUE THREAD

**Issue by odkate** [anddea/revanced-patches#359] opened 2024-04-23 16:11 UTC
### Type

Error at runtime

### Tools used

Revancify

### Application

YouTube 19.10.39, 19.05.36, 19.11.43
patches-v2.224.0-dev.13, patches-v2.224.1-dev.2

### Bug description

When the switch turns on `Append video quality`, the application crashes when launching any video

### Error logs

```shell
04-23 18:50:30.204 19136 19136 E AndroidRuntime: Process: com.google.android.youtube, PID: 19136

04-23 18:50:30.211   714  1626 W ActivityManager:   Force finishing activity com.google.android.youtube/com.google.android.apps.youtube.app.watchwhile.InternalMainActivity
```

### Device Environment

i9506 Android 9

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment] 2024-04-23 17:39
More logs needed. Probably clearing Revancify and repatching might help.

**Comment by Francesco146** [comment] 2024-04-23 17:57
tested on latest dev patches, version v19.14.43, the issue is not reproducible on my part :(

**Comment by odkate** [comment] 2024-04-23 19:46
> repatching

I re-patched it, everything is fine now

**Comment by odkate** [comment] 2024-04-28 07:53
The problem is still relevant, then it appeared again after two restarts of the application

Even in the telegram of inotia00 mentioned this mistake

Then I did not reopen the issue because there are no more errors in the logs

**Comment by odkate** [comment] 2024-04-28 10:43
> 19.10.39, 19.05.36, 19.11.43

on 18.25.40 there is no such problem, but there is another one - a black screen with a loading wheel and no viewing progress

**Comment by anddea** [comment] 2024-04-28 11:18
Crashing should be fixed in the latest release with reverting another bug fix. 

The loading screen like it was before updating to latest GmsCore? Then it is probably related to Google doing something with your account/channel.

**Closed** 2024-04-28 11:18 UTC
Labels: Bug report

**Comment by odkate** [comment] 2024-04-28 11:31
> fixed

patched YouTube v19.05.36 by patches-v2.224.1-dev.4, no crash is observed anymore

**Comment by odkate** [comment] 2024-04-28 11:44
> before updating to latest GmsCore

This issue is on YouTube 18.25.40, observed every time the app is launched, only when you first open the video

I also tried it on the patch version v2.223.0

**Comment by anddea** [comment] 2024-04-28 13:11
Any screenshot or screen record?

**Comment by odkate** [comment] 2024-04-28 13:27
> screenshot

![Screenshot_20240428-162656](https://github.com/anddea/revanced-patches/assets/90364108/2f493f06-5a78-46ea-bd3a-a09ed8419618)

**Comment by anddea** [comment] 2024-04-28 16:37
It looks like the same buffering problem. This happens to some accounts for an unknown reason and later it goes away on its own. But then this should happen with all YT versions. Is it different for a newer version with the same account?

**Comment by odkate** [comment] 2024-04-28 16:41
> for a newer version with the same account

Newer versions of YouTube on the same patches and with the same account work fine

**Comment by anddea** [comment] 2024-04-28 17:03
Did start from dev.3?

**Comment by odkate** [comment] 2024-04-28 17:20
> start

The v2.223.0 patches have buffering, I haven't tried this version of YouTube on earlier ones

**Comment by anddea** [comment] 2024-04-28 17:21
Exclude Return YouTube Dislike and verify if it works without buffering?

**Comment by odkate** [comment] 2024-04-28 17:24
> Exclude Return YouTube Dislike

I always exclude this patch

**Comment by anddea** [comment] 2024-04-28 17:30
Interesting, I can't reproduce this issue. Can you clear patching tool and try again?

**Comment by odkate** [comment] 2024-04-28 17:33
> try again

On the latest dev version?

**Comment by anddea** [comment] 2024-04-28 17:44
Yes

**Comment by odkate** [comment] 2024-04-28 19:49
> clear patching tool and try again

I found out that if you manually select any playback quality(Whether upward or downward), then buffering occurs

Or if you set the playback quality to forced in the ReVanced settings

**Comment by anddea** [comment] 2024-04-28 21:44
Is it happening for 2.224 stable?

**Comment by odkate** [comment] 2024-04-28 22:08
> happening

yes, this happens on different patches starting from v2.223.0, but it may be earlier, because I have not tested it on earlier patches

**Comment by anddea** [comment] 2024-04-28 22:43
Can you test original ReVanced and ReX?

**Comment by odkate** [comment] 2024-04-29 04:59
> ReX

It's the same on this version of YouTube


> ReVanced

![Screenshot_20240429-074208](https://github.com/anddea/revanced-patches/assets/90364108/f0a05bd8-4a6b-4c25-81da-b489139ce9a9)

**Comment by anddea** [comment] 2024-04-29 07:37
Check 18.32. First impression I get that it has to do with new GmsCore. And it'll be the same for some older versions, not just the one you mentioned.

**Comment by odkate** [comment] 2024-04-29 09:58
> Check

I tried it, all the same
But now all the tests are useless, because have started buffering even the previously working version

I tried deleting the account, clearing GMSCore data, and running it with a VPN
But buffering still happens
It seems that the reason is in the device
I will check on another device as soon as possible

**Comment by anddea** [comment] 2024-04-29 10:11
I think Google soft bans channels when testing a lot, creating new channel on the same account should do probably but not sure here.

**Comment by odkate** [comment] 2024-04-29 10:16
> channels

But I tried without an account at all, so I doubt that this is the reason

**Comment by odkate** [comment] 2024-04-30 14:22
> older versions

Buffering is absent now on newer versions of YouTube

On older versions of YouTube, buffering is absent when manually changing the video quality, but there is buffering when set the quality in the Revanced settings

It is unclear why this happens
