### ISSUE TITLE
Bug: patching reddit

### ISSUE THREAD

**Issue by shifoc** [anddea/revanced-patches#443] opened 2024-05-09 19:15 UTC
### Type

Error while patching

### Tools used

Revancify

### Application

Reddit v2024.19.0

### Bug description

Can't patch the app

### Error logs

```shell
│ INFO: Compiled classes.dex                                                                   │
│ INFO: Compiled classes2.dex                                                                  │
│ INFO: Compiled classes3.dex                                                                  │
│ INFO: Compiled classes4.dex                                                                  │
│ INFO: Compiled classes5.dex                                                                  │
│ INFO: Compiled classes6.dex                                                                  │
│ INFO: Compiled classes7.dex                                                                  │
│ INFO: Compiled classes8.dex                                                                  │
│ INFO: Compiled classes9.dex                                                                  │
│ INFO: Compiled classes10.dex                                                                 │
│ INFO: Compiled classes11.dex                                                                 │
│ INFO: Compiled classes12.dex                                                                 │
│ INFO: Compiling modified resources                                                           │
│ WARNING: /data/data/com.termux/files/home/revancify-data/apps/Reddit-2024.19.0/base-RVX-andd │
│ WARNING: /data/data/com.termux/files/home/revancify-data/apps/Reddit-2024.19.0/base-RVX-andd │
│ WARNING: /data/data/com.termux/files/home/revancify-data/apps/Reddit-2024.19.0/base-RVX-andd │
│ WARNING: /data/data/com.termux/files/home/revancify-data/apps/Reddit-2024.19.0/base-RVX-andd │
│ WARNING: error: failed linking references.                                                   │
│ brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit  │
│        at brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:246)                        │
│        at brut.androlib.AaptInvoker.invokeAapt(AaptInvoker.java:391)                         │
│        at app.revanced.patcher.data.ResourceContext.get(ResourceContext.kt:128)              │
│        at app.revanced.patcher.Patcher.get(Patcher.kt:265)                                   │
│        at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:313)                     │
│        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)                       │
│        at picocli.CommandLine.access$1500(CommandLine.java:148)                              │
│        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(Comman │
│        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)                          │
│        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)                          │
│        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)      │
│        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)                         │
│        at picocli.CommandLine.execute(CommandLine.java:2170)                                 │
│        at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:12)                     │
│ Caused by: brut.common.BrutException: could not exec (exit code = 1): [./aapt2, link, -o, /d │
│        at brut.util.OS.exec(OS.java:104)                                                     │
│        at brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:242)                        │
│        ... 13 more
```

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment] 2024-05-09 20:38
Duplicate of https://github.com/anddea/revanced-patches/issues/401

**Closed** 2024-05-09 20:38 UTC
Labels: Bug report
