### ISSUE TITLE
bug: `Hide Disable Comments` does not hide comments that are disabled

### ISSUE THREAD

**Issue by akir45** [anddea/revanced-patches#623] opened 2024-06-19 02:10 UTC
### Type

Cosmetic

### Tools used

RVX Manager

### Application

YouTube v19.20.35
patch v2.226.0-dev.14

### Bug description

`Hide Disable Comments` does not hide comments that are disabled when the application language is Japanese. It works well in English. Also, if the label is 0, it will be hidden even in Japanese.

![Screenshot_2024-06-19-10-58-27-357_anddea youtube](https://github.com/anddea/revanced-patches/assets/91464996/79cb0694-f84f-4f58-9a16-3629c580284c)

Below is a link to the video
https://youtube.com/shorts/vqVjCuty4t0

### Device Environment

android14

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by zerozero0022** [comment] 2024-06-19 08:41
Does this issue happen even if you logged in with a different ID or didn't log in?

I have another issue but I have a view filter issue and another "hide disabled comments" issue but I think it's caused by A/B Test.

**Comment by akir45** [comment] 2024-06-19 09:48
The comment button was not hidden for other accounts or even if you did not log in.

**Comment by anddea** [comment] 2024-06-19 16:03
Seems it was the issue only for Japanese. It should be fixed now, test it and let me know.

**Closed by anddea** 2024-06-19 16:03 UTC
Labels: Bug report

**Comment by akir45** [comment] 2024-06-19 16:26
Works well. Thanks.

**Comment by anddea** [comment] 2024-06-20 08:52
I updated it again, since I noticed issues for other languages as well. 

> I have another issue but I have a view filter issue and another "hide disabled comments" issue but I think it's caused by A/B Test.

What issues? With latest dev patches and integrations?

**Comment by anddea** [comment] 2024-06-20 12:34
Disabled comment button is hidden with latest patches and integrations too? Because on my side it works now as expected, for old, new accounts and your language. I'll look into filtering by views later.

**Comment by zerozero0022** [comment] 2024-06-20 20:20
patches dev.15 + integrations dev.8 ...

not fixed ...

**Comment by anddea** [comment] 2024-06-21 08:47
Seems I cannot reproduce it. I tested on old, new and brand accounts. If you want to test it, let me know, I'll add more debug messages.
