### ISSUE TITLE
Patching Reddit v.2024.18.0 fails. Please add support for this version, thanks.

### ISSUE THREAD

**Issue by n4zk4** [anddea/revanced-patches#410] opened 2024-05-01 03:38 UTC
### Type

Error while patching

### Tools used

RVX Manager

### Application

Reddit v.2024.18.0 (patches v2.225.0-dev.2)

### Bug description

Patching Reddit v2024.18.0 fails (with patches v2.225.0-dev.2).

I've tried twice, even removing the obsolete patch Hide Toolbar Buttons, but same result. First time ever, for me, that patching fails.

### Error logs

```shell
- Device Info
ReVanced Manager: 1.18.1
Model: SM-S916B
Android version: 14
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.reddit.frontpage v2024.18.0 (Suggested: Any)
Patches version: v2.225.0-dev.2
Patches added: Default
Patches removed: Hide toolbar button
Default patch options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: false
Show universal patches: false
Remove unused library: false
Patches source: anddea/revanced-patches
Integration source: anddea/revanced-integrations

- Logs
Copying APK
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing resource cache directory
Decoding resources
Executing patches
Applied 10 patches
Compiling patched dex files
Compiled 12 dex files
Compiling modified resources
An error occurred:
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~CYMoM9Y61UMHSUtzX6gvSg==/app.rvx.manager.flutter-xtZM6ISG20ETbrMfL8NlfA==/lib/arm64/libaapt2.so, link, -o, /data/user/0/app.rvx.manager.flutter/cache/patcher/tmp-PULYON/cache/aapt_temp_file, --package-id, 127, --min-sdk-version, 26, --target-sdk-version, 34, --version-code, 1577901, --version-name, 2024.18.0, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.rvx.manager.flutter/cache/APKTOOL4484027058307580606.tmp, -0, arsc, -I, /data/user/0/app.rvx.manager.flutter/cache/patcher/tmp-PULYON/cache/1.apk, --manifest, /data/user/0/app.rvx.manager.flutter/cache/patcher/tmp-PULYON/cache/AndroidManifest.xml, /data/user/0/app.rvx.manager.flutter/cache/patcher/tmp-PULYON/cache/build/resources.zip]
	at brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:246)
	at brut.androlib.AaptInvoker.invokeAapt(AaptInvoker.java:391)
	at app.revanced.patcher.data.ResourceContext.get(ResourceContext.kt:128)
	at app.revanced.patcher.Patcher.get(Patcher.kt:265)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$37(MainActivity.kt:375)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$v-ELoclvC6W1vrKGstBtHifiD5Q(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda0.run(Unknown Source:26)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~CYMoM9Y61UMHSUtzX6gvSg==/app.rvx.manager.flutter-xtZM6ISG20ETbrMfL8NlfA==/lib/arm64/libaapt2.so, link, -o, /data/user/0/app.rvx.manager.flutter/cache/patcher/tmp-PULYON/cache/aapt_temp_file, --package-id, 127, --min-sdk-version, 26, --target-sdk-version, 34, --version-code, 1577901, --version-name, 2024.18.0, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.rvx.manager.flutter/cache/APKTOOL4484027058307580606.tmp, -0, arsc, -I, /data/user/0/app.rvx.manager.flutter/cache/patcher/tmp-PULYON/cache/1.apk, --manifest, /data/user/0/app.rvx.manager.flutter/cache/patcher/tmp-PULYON/cache/AndroidManifest.xml, /data/user/0/app.rvx.manager.flutter/cache/patcher/tmp-PULYON/cache/build/resources.zip]
	at brut.util.OS.exec(OS.java:104)
	at brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:242)
	... 7 more
```

### Device Environment

Android 14, OneUI 6.1

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment] 2024-05-01 07:51
Duplicate of #401. Continue discussion there.

**Closed** 2024-05-01 07:52 UTC
Labels: Bug report
