### ISSUE TITLE
bug: Default YT version is back to 19.16.39

### ISSUE THREAD

**Issue by AbakNacchan** [anddea/revanced-patches#731] opened 2024-07-14 21:59 UTC
### Type

Error while patching

### Tools used

CLI

### Application

[v2.227.0-dev.20](https://github.com/anddea/revanced-patches/releases/tag/v2.227.0-dev.20)

### Bug description

When using extensive builder using CLI, the default YT version is back to 19.16.39, not the latest supported one.

### Error logs

```shell
[+] Getting prebuilts (anddea)
2024-07-14 15:55:24 URL:https://api.github.com/repos/inotia00/revanced-cli/releases/latest [4123/4123] -> "-" [1]
2024-07-14 15:55:24 URL:https://api.github.com/repos/anddea/revanced-integrations/releases/tags/v0.154.0-dev.6 [6793/6793] -> "-" [1]
2024-07-14 15:55:24 URL:https://api.github.com/repos/anddea/revanced-patches/releases/tags/v2.227.0-dev.20 [9070/9070] -> "-" [1]
2024-07-14 15:55:24 URL:https://www.apkmirror.com/apk/google-inc/youtube/ [437180] -> "-" [1]
[+] Choosing version '19.16.39' for YouTube
```

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment] 2024-07-15 06:40
When you create a new issue, you mark the checkbox 'This issue is not a duplicate of an existing bug report'. However, this issue is a duplicate and has already been addressed. This is not a bug. Support has been dropped due to numerous A/B tests. You can still patch version 19.28, but it is not fully supported by us. This means that no bug reports for versions above 19.16 will be accepted.

**Closed by anddea** 2024-07-15 06:40 UTC
Labels: Bug report

**Comment by anddea** [comment] 2024-07-19 06:07
Just uninstall and install the new one. You can export settings before that and then import after new installation.
