### ISSUE TITLE
bug(YouTube): Custom Branding Heading + Header Switch

### ISSUE THREAD

**Issue by zerozero0022** [anddea/revanced-patches#140] opened 2024-03-24 22:22 UTC
### Type

Error while patching

### Tools used

RVX Manager

### Application

YouTube

### Bug description

Header Switch does not work with app that include Custom Branding Heading and Header Switch.

Can't you fix it by setting Default to Custom Head and Premium Head to Premium Head for apps with both patches?

and

I'd like to see the header patch applied to the logo in the sidebar that appears when press the navigation button in the category bar.

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by n1cKz1** [comment] 2024-04-12 21:49
On v.2.224.0-dev.2 I could use both non-premium and premium custom headers when switching headers, but on v.2.224.0-dev.3 only the non-premium custom header shows even if premium header is enabled

**Comment by anddea** [comment] 2024-04-23 18:43
@n1cKz1 there were no changes for header. It shows premium header if enabled on my side. Do you still encounter this issue?

**Comment by anddea** [comment] 2024-04-25 07:47
I tested it and it works, although in dev3 the patch was renamed from `Custom branding heading` to `Custom branding wordmark header`, maybe that's the reason why it stopped working, clearing patch options should help then.

**Comment by STEK1337** [comment] 2024-04-25 11:27
Tested with CLI latest dev patches `revanced-patches-2.224.0-dev.16.jar` and it works, I think as @anddea said the issue was the name of the patch. Previously it was `Custom branding heading`, now its `Custom branding wordmark header`. The `key` value for `Custom branding wordmark header` has not been changed so the problem is not in `options.json` but in the new patch name for custom header. @n1cKz1 try patching with `Custom branding wordmark header` and report if its working

**Comment by n1cKz1** [comment] 2024-04-25 17:30
I patched with RVX Manager which showed even the dev versions for some reason and it wouldn't work. I will try later tonight using CLI or official ReVanced Manager and I'll let you know

**Comment by anddea** [comment] 2024-04-25 17:42
> I patched with RVX Manager which showed even the dev versions for some reason and it wouldn't work. I will try later tonight using CLI or official ReVanced Manager and I'll let you know

You have to clear it then. It works in RVX Manager as well.

**Comment by n1cKz1** [comment] 2024-04-26 00:45
I did a clean re-install of RVX manager and I still couldn't get it to work. Only the non-premium one is showing still. I even tried doing the patching process with an emulator or patching with official manager, same thing. I believe another patch might be interfering with this, causing the premium header not to be ignored for whatever reason, because like I said:

> Also it's noteworthy that even back on v.2.224.0-dev.2 when it worked, for some reason it only worked if I chose a preset custom branding icon option. If I provided the files myself for custom branding icon then only the non-premium header showed, like now. No idea why this happened as they are 2 separate patches

**Comment by anddea** [comment] 2024-04-26 06:52
What custom icon/header do you use?

**Comment by STEK1337** [comment] 2024-04-26 08:13
Wait, you are talking about the toggle in `Revanced Extended` settings ---> `General` ---> `Premium Header`

If I choose `Premium Header` to be shown it still shows the custom one.
@n1cKz1 are we talking about this?

**Comment by n1cKz1** [comment] 2024-04-26 11:33
> @n1cKz1 are we talking about this?

Yes lol, I thought that was clear by now. You could use both premium and non premium custom headers simultaneously. Premium header file goes by this name:

yt_premium_wordmark_header_dark (or light for light mode)

**Comment by STEK1337** [comment] 2024-04-26 11:49
Yes, its bugged. No matter if I select `Premium Header` to be shown it still shows `Custom Header`
Either the `Custom branding wordmark header` or `Header switch` needs to be updated
@anddea

**Comment by anddea** [comment] 2024-04-26 12:09
But why would you use both of them? They do exactly the same, the one forces it and the second adds the switch.

**Comment by n1cKz1** [comment] 2024-04-26 12:12
The idea is to be able to switch between 2 custom non premium and premium headers with the header switch.

As for the motivation, it's essentially the same as only using the header switch patch in general, just with custom headers instead lol

**Comment by STEK1337** [comment] 2024-04-26 12:50
Im only using the custom header, don't need premium
@n1cKz1 here is your answer

**Comment by anddea** [comment] 2024-04-26 13:06
If I remember correctly, custom header adds only one header, it's made for people who wants to switch to premium or use their own custom header, just one at the time. It comes from RVX by default as it is right now. 

It is a forcible patch and an alternative to header switch. They weren't meant to work together. So it's not a bug, it should be feat (feature request) then. 

Although, if you you use custom branding icon, except for Revancify, all of them have both versions, YouTube and Premium headers. But you cannot add your own custom icons for header there, only launcher icons can be added. It's a questionable thing, should I add support there and you'll have to provide all icons together, including launcher, splash and header, most of the people won't use that.

**Comment by anddea** [comment] 2024-04-26 13:54
Header switch was added not long ago, maybe in 2.222, before that there was only custom branding heading which added only selected header in a patching tool. 

I'm gonna close this, the author can reopen it after renaming it to feat and adding feature request label but tbh I see no point to do this. If you have any Custom branding icons that is consistent everywhere, which means you have launcher, splash, header icons, then we can add it to `Custom branding icon` instead.

**Closed** 2024-04-26 13:55 UTC
Labels: Bug report
