### ISSUE TITLE
Backup corrups itself

### ISSUE THREAD

**Issue by speedlorenzo12** [anddea/revanced-patches#159] opened 2024-03-26 15:42 UTC
### Type

Other

### Tools used

Revancify

### Application

Latest supported

### Bug description

When I change a setting in YouTube and then create a backup and it mistypes the code when overwriting it with the previous backup 
For me this:(  "sb_music_offtopic": "manual-skip"sb_music_offtopic": "manual-skip", )

### Device Environment

Android 13 miui 14

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment] 2024-03-27 17:49
Could you please elaborate?
Maybe screenshots or screen record?

Is it duplicated?

**Comment by speedlorenzo12** [comment] 2024-03-27 19:10
I can tell you how to reproduce it because it's a bug that happens randomly:
1. Export the settings
2.change setting
3.export the settings again, overwriting the previous export
4.try to import the settings, if it succeeds in importing the settings it returns to stage 2

**Comment by anddea** [comment] 2024-03-29 19:50
What file manager do you use? I don't really understand the issue. I export settings and everything works fine. Though it won't overwrite exported settings in my case in default files.

**Comment by speedlorenzo12** [comment] 2024-03-29 19:51
The Huawei file manager

**Comment by Francesco146** [comment] 2024-05-10 11:53
from what I understood, it's the intended behavior. not a bug, consider closing this

**Closed** 2024-05-10 15:42 UTC
Labels: Bug report
