### ISSUE TITLE
feat: Search for patches option

### ISSUE THREAD

**Issue by 54m4d** [anddea/revanced-patches#440] opened 2024-05-08 22:16 UTC
### Application

YouTube

### Feature description

Hello, Today, I'd like to propose a feature that enables searching for patches based on keywords entered into the search field. This would simplify the process of finding desired patches, eliminating the need to manually navigate through all the sections.

### Motivation

With over 100 patches available for e.g. YouTube, locating a specific patch can be challenging, especially if the user is unsure of its section. Implementing a search function would effortlessly resolve this issue.

<details>
<summary>Something that looks similar to this</summary>
<img src=https://github.com/anddea/revanced-patches/assets/52612348/1ad37a1a-3a81-4d4e-b7b8-e4589e5420ac>
</details>

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by akir45** [comment] 2024-05-08 23:02
Duplicate of #68

**Closed** 2024-05-09 06:48 UTC
Labels: Feature request
