### ISSUE TITLE
Reddit: severe patching issue

### ISSUE THREAD

**Issue by JakobHunterek** [anddea/revanced-patches#373] opened 2024-04-25 21:45 UTC
### Type

Error while patching

### Tools used

Revancify

### Application

2024.17.0.1568106

### Bug description

The Hide Toolbar button patch fails to install

### Error logs

```shell
INFO: Loading patches 
INFO: Decoding app manifest 
INFO: Custom branding name Reddit excluded 
INFO: Change package name excluded 
INFO: Setting patch options 
INFO: Merging integrations 
INFO: Deleting existing resource cache directory 
INFO: Decoding resources 
INFO: Executing patches 
INFO: Disable screenshot popup succeeded 
INFO: Hide ads succeeded 
INFO: Hide navigation buttons succeeded 
INFO: Hide recently visited shelf succeeded 
SEVERE: Hide toolbar button failed:
app.revanced.patcher.patch.PatchException: Failed to resolve HomePagerScreenFingerprint
	at app.revanced.util.BytecodeUtilsKt.getException(BytecodeUtils.kt:27)
	at app.revanced.patches.reddit.layout.toolbar.ToolBarButtonPatch.execute(ToolBarButtonPatch.kt:50)
	at app.revanced.patches.reddit.layout.toolbar.ToolBarButtonPatch.execute(ToolBarButtonPatch.kt:18)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:174)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:203)
	at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
	at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
	at app.revanced.cli.command.PatchCommand$run$4$patcherResult$1$1.invokeSuspend(PatchCommand.kt:304)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:303)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:12)
 
INFO: Open links directly succeeded 
INFO: Open links externally succeeded 
INFO: Premium icon succeeded 
INFO: Remove subreddit dialog succeeded 
INFO: Sanitize sharing links succeeded 
INFO: Settings succeeded 
INFO: Compiling patched dex files 
INFO: Compiled classes.dex 
INFO: Compiled classes2.dex 
INFO: Compiled classes3.dex 
INFO: Compiled classes4.dex 
INFO: Compiled classes5.dex 
INFO: Compiled classes6.dex 
INFO: Compiled classes7.dex 
INFO: Compiled classes8.dex 
INFO: Compiled classes9.dex 
INFO: Compiled classes10.dex 
INFO: Compiled classes11.dex 
INFO: Compiled classes12.dex 
INFO: Compiled classes13.dex 
INFO: Compiled classes14.dex 
INFO: Compiling modified resources 
INFO: Aligning base.apk 
INFO: Signing base.apk 
INFO: Saved to /data/data/com.termux/files/home/revancify-data/apps/Reddit-2024.17.0/base-RVX-anddea.apk 
INFO: Purging temporary files 
INFO: Purged resource cache directory 



Rooted: false
Arch: arm64-v8a
App: Reddit v2024.17.0
CLI: inotia00-cli-v4.4.1.jar
Patches: anddea-patches-v2.224.0.jar
Integrations: anddea-integrations-v0.151.0.apk
Patches argument: -i Disable screenshot popup -i Hide ads -i Hide navigation buttons -i Hide recently visited shelf -i Hide toolbar button -i Open links directly -i Open links externally -i Premium icon -i Remove subreddit dialog -i Sanitize sharing links -i Settings
```

### Solution

None

### Additional context

None

### Device Environment

Android 14 OneUI 6.0

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by shifoc** [comment] 2024-04-25 21:52
i have the same issue

**Comment by anddea** [comment] 2024-04-26 06:50
Duplicate of #327. Continue there.

**Closed by anddea** 2024-04-26 06:50 UTC
Labels: Bug report

**Comment by anddea** [comment] 2024-04-26 07:11
Do you see those buttons in toolbar without this failing patch?
