### ISSUE TITLE
Yt music patches.

### ISSUE THREAD

**Issue by UniverseCodex01** [anddea/revanced-patches#31] opened 2024-03-12 16:02 UTC
### Type

Error while patching

### Tools used

Revancify

### Application

com.google.android.apps.youtube.music 6.43.52

### Bug description

Return old style minimised player, Change start page and other patches aren't working on newer Yt music versions(get error during patch process).

### Error logs

```shell
None.
```

### Solution

None.

### Additional context

None.

### Device Environment

Android 10, Miui 12.5.3 EU

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment] 2024-03-13 09:25
Duplicate of https://github.com/anddea/revanced-patches/issues/17.

**Closed by anddea** 2024-03-13 09:25 UTC
