### ISSUE TITLE
bug: "Hide navigation buttons" crashes youtube

### ISSUE THREAD

**Issue by SigmoidZebra844** [anddea/revanced-patches#312] opened 2024-04-13 17:02 UTC
### Type

Error at runtime

### Tools used

RVX Manager

### Application

youtube 19.05.36 and 19.11.38

### Bug description

having "Hide navigation buttons" patch enabled causes the application to crash on boot.

### Solution

don't use the patch but lose the ability to change the nav buttons

### Additional context

Error log too long so i added a file
[log.txt](https://github.com/anddea/revanced-patches/files/14968143/log.txt)

### Device Environment

Xiaomi 13 8gb ram hyperos 1.0.8.0 by xiaomi.eu rooted with magisk v27 and a shit ton of modules, Yuni-5.15 Beta 24.03.30 kernel, a lot of miui related magisk module like mod for launcher, zygisk detach, scene7 app, twrp recovery. play integrity passes and even google wallet works fine.

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment] 2024-04-13 17:50
Did you notice this error before with previous patches? 

Try to clear Manager and YouTube.

**Comment by Fred6388** [comment] 2024-04-14 01:22
I have the same issue

**Comment by anddea** [comment] 2024-04-14 06:18
Can you grab logs with logcat? 

Can you reproduce this crash with original ReVanced with latest dev?

**Comment by anddea** [comment] 2024-04-14 07:28
@SigmoidZebra844 your logs show error with the function that was replaced in the latest release, it should've migrated but it didn't for some reason. So clearing YouTube cache and data can help in your case.

**Comment by SigmoidZebra844** [comment] 2024-04-14 11:05
Just used revancify to patch using latest dev 2.224.0-dev.4 on 19.11.38 with all patches (except microg, tack away pref, hide player chapter and the one thats not compatible with this version) and everything works perfectly now. btw there was another problem, when i found that hide nav buttons was causing the crash and i patched with all patches but that one and the revanced settings page was blank. I quickly found the cause to be alternative thumbnails, and now that i patched using dev this was also fixed.

**Comment by anddea** [comment] 2024-04-15 06:32
I patched dev2 and updated with dev4 on top of it and couldn't reproduce it, maybe it has to do with the mounting of Manager. After you tried Revancify and everything works fine, can you also repatch with Manager again just to check if it's fixed with it too? Maybe clearing temporary files in Manager settings can help.

**Comment by Francesco146** [comment] 2024-04-17 15:30
not reproducible on latest dev-patch and version 19.11.38

**Comment by anddea** [comment] 2024-04-17 15:42
I'm gonna close it, because I couldn't reproduce it too. But I feel that some people will get this error when it goes stable. Unfortunately, we couldn't understand the cause but my guess it's a patching tool that cached old files.

**Closed** 2024-04-17 15:42 UTC
Labels: Bug report

**Comment by Francesco146** [comment] 2024-04-17 15:46
> Unfortunately, we couldn't understand the cause but my guess it's a patching tool that cached old files.

if they're using my RVX manager, yeah it's not stable for now. It works 80% of the times

**Comment by anddea** [comment] 2024-04-17 15:50
All tools have caching issues, you have to delete temporary files from time to time.
