### ISSUE TITLE
bug: Hide player buttons background toggle doesn't work with film strip overlay button.

### ISSUE THREAD

**Issue by Pikasatupu75** [anddea/revanced-patches#333] opened 2024-04-17 21:25 UTC
### Type

Cosmetic

### Tools used

RVX Manager

### Application

YouTube 19.05.36
ReVanced Patches 2.224.0-dev.8
ReVanced Integrations 0.151.0-dev.7

### Bug description

Turning on 'Hide player buttons background' setting in player settings doesn't work on film strip overlay button.
![Screenshot_20240418-001812_ReVanced Extended](https://github.com/anddea/revanced-patches/assets/126986435/f8ba705a-1c6e-4826-870d-44809e5c4bd6)
![Screenshot_20240418-001815_ReVanced Extended](https://github.com/anddea/revanced-patches/assets/126986435/b68be17a-cdf8-4fb4-9d02-548f54ee589e)

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Francesco146** [comment] 2024-04-19 19:30
unable to reproduce on version 19.11.38, consider updating

**Comment by Francesco146** [comment] 2024-04-22 20:47
have you tried updating to v19.14.43? is this issue still happening to you?

**Comment by Pikasatupu75** [comment] 2024-04-23 07:19
OK, I updated to v19.14.43 and the same bug is still happening. To clarify, I am not using the "Force hide player background buttons background" patch. I am using the "Hide player buttons background" patch.

**Comment by Francesco146** [comment] 2024-04-23 07:32
> OK, I updated to v19.14.43 and the same bug is still happening. To clarify, I am not using the "Force hide player background buttons background" patch. I am using the "Hide player buttons background" patch.

i included both patches and I'm not having this issue. backup your settings and give that patch a shot

**Comment by Pikasatupu75** [comment] 2024-04-23 08:43
Yeah, including both patches hides the flim strip overlay button. But I think we are not supposed to include them together. Because the force patch breaks the toggle patch and hides the buttons permanently.

**Comment by Francesco146** [comment] 2024-04-23 09:43
> the force patch breaks the toggle patch and hides the buttons permanently.

you're right, hopefully this will be fixed in a future release

**Closed** 2024-05-26 10:24 UTC
Labels: Bug report

**Comment by Pikasatupu75** [comment] 2024-05-26 10:26
This is not an issue anymore since so much changed.
