### ISSUE TITLE
bug: The beginning of Shorts loops several times.

### ISSUE THREAD

**Issue by Quasar-0330** [anddea/revanced-patches#75] opened 2024-03-17 19:41 UTC
### Type

Error at runtime

### Tools used

CLI

### Application

YouTube v19.09.37

### Bug description

When using Wi-Fi, if the default image quality is set to a setting other than "automatic", the beginning of Shorts will loop several times.

### Device Environment

Redmi Note 9S
crDroid 10.2

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment] 2024-03-27 21:24
I tried and tested for several days but still couldn't reproduce this issue. Do you still face it?

**Comment by Quasar-0330** [comment] 2024-03-28 09:59
https://github.com/anddea/revanced-patches/assets/95518809/6fe56c09-05f4-4c7f-a7bc-d2a03fa004c7

Yes. The beginning loops like this

**Comment by anddea** [comment] 2024-03-28 11:29
Is it different for stock YouTube? Can you test whether this issue persists if you:
1.  Exclude `shorts overlay buttons`?
3. Exclude `hide shorts components`?
4. Exclude `disable shorts on startup`?

**Comment by Quasar-0330** [comment] 2024-03-28 20:01
Stock YouTube can play videos normally.
I tested excluding 1, 2, and 3, but no improvement.

**Comment by anddea** [comment] 2024-03-29 06:52
> Stock YouTube can play videos normally. I tested excluding 1, 2, and 3, but no improvement.

Unfortunately, I can't reproduce this issue, so you have to help me to find the root of this problem. Can you exclude maybe `Settings icons` patch (though it shouldn't affect in any way), maybe disable `Spoof player parameters` (I don't remember now but I think it gets applied to Shorts too)?

**Comment by Quasar-0330** [comment] 2024-03-29 13:59
I tried everything and could not see any improvement. However, I am using j-hc/revanced-magisk-module and building it as a Magisk module, and when I try to build it as an apk, the problem does not occur anymore.

**Comment by anddea** [comment] 2024-03-29 14:45
> I tried everything and could not see any improvement. However, I am using j-hc/revanced-magisk-module and building it as a Magisk module, and when I try to build it as an apk, the problem does not occur anymore.

Does not occur when using magisk module or contrary, not using magisk module?

**Comment by Quasar-0330** [comment] 2024-03-31 12:08
Occurs when using the magisk module

**Comment by anddea** [comment] 2024-03-31 21:12
> Occurs when using the magisk module

Try to open issue there. Double check if it doesn't occur by using Manager or Revancify: non-root and root.

**Comment by Zonkerus** [comment] 2024-04-11 21:04
Hi!

I also encountered the shorts looping bug on my smartphone. The model is Samsung A50
The bug appears on both versions (non-root | root), different versions of Android (11 | 12), on different firmware (Official | FreshROM)
Looping usually starts either immediately after installation or after some time

I noticed that looping occurs after the "Downloads" item appears in the YouTube settings ("Settings" - "General")

However, the exception is YouTube versions up to 19.04.38 (inclusive)
Although the "Downloads" item appears on them, looping does not occur

Video demonstrations:

[№1](https://drive.google.com/file/d/1R_sTiv6QVstYyfbKZKl_PuqPdAAQbwT6/view) - Normal installation of YouTube version 19.11.38 (without the "Downloads" item and looping)
[№2](https://drive.google.com/file/d/1KTkkdoZ3S6yUr-AP8gUb-QQEPEoMF_gA/view) - The "Downloads" item appears immediately after installation, there is looping

[№3](https://drive.google.com/file/d/1dX62IKPHH82xBIdNe1dMPqChQ_Nhjvpm/view) - Normal installation of YouTube version 19.04.38 (without the "Downloads" item and looping)
[№4](https://drive.google.com/file/d/11ABQbKBBCzS9pWLrzsNE1CM0KLyl0uHO/view) - The "Downloads" item appears immediately after installation, but without looping

[№5](https://drive.google.com/file/d/1Czc7FdpBDnfNmXCmWnOq9RnDNNFxbiKf/view) - Update from version 19.04.38 to 19.11.38. The "Downloads" item remains, but there is no looping
[№6](https://drive.google.com/file/d/15GpQlhfG4oiYkexCMOtpmmQzJZCBvvax/view) - Downgrade from version 19.11.38 to 19.04.38. The "Downloads" item and looping remain

[№7](https://drive.google.com/file/d/1KtoYCz4bqUh0ghXANWpA59sw3-W-sgvl/view) - Here you can see that looping starts with version 19.05.36

I hope this information will help in solving the problem..
[I apologize if the text is unclear, this is a translation.]

**Comment by anddea** [comment] 2024-04-12 08:01
@Zonkerus did you set default quality to anything other than auto (Settings > Extended > Video > Default video quality)? Seems some people encounter this issue only when changing default quality.

**Comment by Zonkerus** [comment] 2024-04-12 08:29
> @Zonkerus did you set default quality to anything other than auto (Settings > Extended > Video > Default video quality)? Seems some people encounter this issue only when changing default quality.

@anddea
For the demonstration, I only used these settings: 
![image](https://github.com/anddea/revanced-patches/assets/166645857/7f8a965b-c08c-4bc1-af8a-6a25fd017fbb)

I know the looping starts if you put a different quality instead of "Auto".

However, I think this is not a cause, but a consequence. In the video I attached in the comments, you can see that it has something to do with the "Downloads" item in the settings, as well as with the version of YouTube:

1. Even if this item appears in version 19.04.38, and I set a different (other than Auto) quality, the looping does not happen.
2. If I upgrade from version 19.04.38 (which has this item) to version 19.11.38, there is no looping either
3. If I make a downgrade from 19.11.38 to 19.04.38, the loops appear.

Perhaps the reason is that "Restart to load the interface in normal mode" is not working properly on versions above 19.04.38, but that doesn't explain why the "Downloads" item (and with it the loops) appears after some time.... (it's possible that at some point the interface doesn't load correctly, and the settings break because of it - this at least explains why in the case of a downgrade to 19.04.38 the loops remain).

I understand if you don't really want to deal with this problem (after all, it is reproduced only on some smartphones, and on the 4PDA forum only 15 people have had it for a month), but if you need - I can try to make logs, throw the /data folder of the version on which the loops appeared, etc.

**Comment by anddea** [comment] 2024-04-12 16:05
I'll take a look. At the moment, I cannot reproduce this issue in my accounts, so I cannot proceed to fix it. Although that could be a quality issue, because shorts can load videos and only then change the quality. This may also be related to the AV1 codec. Can you also check if you encounter this issue when you enable `Skip preloaded buffer` in Settings > Extended > Video?

**Comment by Zonkerus** [comment] 2024-04-12 17:07
> I'll take a look. At the moment, I cannot reproduce this issue in my accounts, so I cannot proceed to fix it. Although that could be a quality issue, because shorts can load videos and only then change the quality. This may also be related to the AV1 codec. Can you also check if you encounter this issue when you enable `Skip preloaded buffer` in Settings > Extended > Video?

Checked, `Skip preloaded buffer` does not fix the loops

**Comment by Zonkerus** [comment] 2024-04-13 21:30
@anddea, it's me again x)

I was able to reproduce the bug on Redmi Note 10S (no loops on it) by restoring the app data from a smartphone backup using Neo-Backup

I'm attaching the video (And also the archive with the backup).

At the very beginning you can see that there is no looping behavior despite the presence of the Downloads item in version 19.11.38. (00:00 - 00:30)

However, after the restore, the same behavior as on my smartphone starts (00:52)

I have done some tests and usually the error occurs immediately after the restore, but once I had to repeat the restore 2-3 times

I hope this helps to reproduce the bug on your devices

I used the following apps
https://github.com/ReVanced/GmsCore/releases
https://github.com/Zonkerus/Test/releases/download/2/youtube-revanced-extended-v19.11.38-all.apk
https://github.com/NeoApplications/Neo-Backup/releases/download/8.3.6/Neo_Backup_836_release.apk

Backup: [anddea.youtube.zip](https://github.com/anddea/revanced-patches/files/14968660/anddea.youtube.zip)

https://github.com/anddea/revanced-patches/assets/166645857/c7548af3-139e-4d76-b0ad-3d1b5c595c6d

**Comment by Zonkerus** [comment] 2024-04-14 21:57
Well..

Moving shared_prefs/youtube.xml from 19.04.38 to 19.11.38 fixes the loops for about a minute, then the file is overwritten and the loops return

Tried excluding patches as well, down to just leaving "'Default video quality' 'Settings'", but that didn't work

The "Bug description" literally looks something like this:
The "Default video quality" patch on YouTube versions above 19.04.38 does not work properly on some devices, causing shorts to loop at the beginning of playback

**Comment by Zonkerus** [comment] 2024-04-18 01:43
I don't know if these logs will help (I did some filtering, otherwise the files were a mess), but here are my steps:

1. I minimized the app on the "You" tab, replaced the youtube.xml file, opened the app.
2. Started Shorts (the loops are in place).
3. I minimized the app on the Shorts tab, replaced the file again, and opened the app.
4. Started Shorts (no loops).
5. Opened the "You" tab.
6. Started Shorts (there are loops).

In the second folder "Normal" the same order of actions, but I did not replace the file (i.e. just minimized and opened the application), but in this case in the settings item "Downloads" has not appeared yet

In the third "Root" folder, it's the same, but the root version 19.04.38 is there.

I will leave this issue at this time, I have no more information to share 😵

[Logs.zip](https://github.com/anddea/revanced-patches/files/15018768/Logs.zip)

**Comment by anddea** [comment] 2024-04-18 09:09
Can you verify if this bug is present in original ReVanced? 

It's definitely account/channel related. Don't know if it matters to you but your files have some personal information, e.g. email.

**Comment by Zonkerus** [comment] 2024-04-18 15:21
> Can you verify if this bug is present in original ReVanced?

Checked. On ReVanced there are no problems, the item "Downloads" does not cause looping. The problem is observed only in ReVanced Extended.

By the way, you were right about the account. For some reason I didn't consider it as the source of the problem, but I should have....

Anyway, first I created a new account and checked if my smartphone would loop - **it did not loops**
Then I decided to check if other smartphones (specifically Poco M5 and Redmi Note 10S) would start to loops if I logged in from my account - **they did.**

I don't know what Google slipped into my account, or why it's causing the loops on versions above 19.04.38 (with the "Downloads" item), but in theory it's a potential source of problems in the future

If you have any thoughts on this, I can provide my account (just don't break it, okay? ツ)

> Don't know if it matters to you but your files have some personal information, e.g. email.

It doesn't really bother me x)

**Comment by anddea** [comment] 2024-04-18 15:59
> On ReVanced there are no problems

Just to clarify, you used the same account where you encountered loops, you changed default quality in settings and you don't get loops in original ReVanced, right?

**Comment by Zonkerus** [comment] 2024-04-18 16:04
> Just to clarify, you used the same account where you encountered loops, you changed default quality in settings and you don't get loops in original ReVanced, right?

That's right

**Comment by Zonkerus** [comment] 2024-04-18 16:30
>Anyway, first I created a new account and checked if my smartphone would loop - it did not loops

>Then I decided to check if other smartphones (specifically Poco M5 and Redmi Note 10S) would start to loops if I logged in from my account - they did

Just in case, I should clarify that before logging into the account (both new and main), I did a data reset in the app to make it behave the same as when I first started it.

If I logged into the new account and then switched to the main one, I didn't get any loops (though it didn't last long, but the effect lasted longer than when I switched youtube.xml, it even survived going to the "You" menu).

If you do the opposite, then accordingly on the new account there will be looping (but it is not fixed on it, after data reset everything is okay).

**Comment by anddea** [comment] 2024-04-20 09:49
@Zonkerus I matched some part of the code to the original ReVanced code, can you test it if it fixes the issue?

**Comment by Zonkerus** [comment] 2024-04-20 16:32
> @Zonkerus I matched some part of the code to the original ReVanced code, can you test it if it fixes the issue?

Strangely, that didn't help, I'm still encountering the looping issue

I wanted to re-check if the loops would occur if I excluded all patches except "'Custom package name' 'Settings' 'Default video quality'", but I got this error:

```
 SEVERE: Default video quality failed:
 app.revanced.patcher.patch.PatchException: lateinit property playerInitMethod has not been initialized
 	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:187)
 	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:205)
 	at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
 	at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
 	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
 	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
 	at app.revanced.cli.command.PatchCommand$run$4$1$1.invokeSuspend(PatchCommand.kt:314)
 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
 	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
 	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
 	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
 	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
 	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
 	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
 	at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:313)
 	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
 	at picocli.CommandLine.access$1500(CommandLine.java:148)
 	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
 	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
 	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
 	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
 	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
 	at picocli.CommandLine.execute(CommandLine.java:2170)
 	at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:12)
 Caused by: kotlin.UninitializedPropertyAccessException: lateinit property playerInitMethod has not been initialized
 	at app.revanced.patches.youtube.utils.videoid.general.VideoIdPatch.onCreateHook$revanced_patches(VideoIdPatch.kt:231)
 	at app.revanced.patches.youtube.video.quality.RememberVideoQualityPatch.execute(RememberVideoQualityPatch.kt:69)
 	at app.revanced.patches.youtube.video.quality.RememberVideoQualityPatch.execute(RememberVideoQualityPatch.kt:25)
 	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:173)
 	... 24 more
```

This was not the case with dev-9 (and previous patches)..

If I do not exclude patches, the build goes fine

Video:

https://github.com/anddea/revanced-patches/assets/166645857/c2e36b78-d2d0-4553-bd09-381e3d0a3ed5

P.S: while watching it, I noticed that on the original ReVanced, at 0:54, when I start the Shorts tab, there is some kind of microlag that occurs if I minimize the application and force close the application (it occurs "once" and does not manifest itself in any other way, and so on until the next restart of the application)

I honestly don't remember if it was like this before, but it's also account related, I've checked.. 😐

**Comment by anddea** [comment] 2024-04-20 17:29
For now default video quality will fail without default playback speed (and maybe some other patch, not sure). But I'll revert back last release and will try something different. If you patch with only those 2 patches let me know the results of testing. 

I see ReVanced has a little loop for the first Shorts video, does it happen every time you start playing first video in Shorts or only this time?

**Comment by Zonkerus** [comment] 2024-04-20 18:37
> fail without default playback speed

Yes, added that patch, now the build was successful

When using "'Custom package name' 'Settings' 'Default video quality' 'Default playback speed'", there was **no looping** (except for a microglitch like in the original ReVanced).

>I see ReVanced has a little loop for the first Shorts video, does it happen every time you start playing first video in Shorts or only this time?

To avoid confusion, I'd rather just show it on video

https://github.com/anddea/revanced-patches/assets/166645857/7b9f8b08-faff-4ddd-91c7-3a9665f2a16b

I'll try to create builds with different patches now and see if any particular one causes looping

**Comment by anddea** [comment] 2024-04-20 19:18
> I'll try to create builds with different patches now and see if any particular one causes looping

That would be helpful. Thank you. My accounts don't have this issue so it's hard to determine on my side.

**Comment by Zonkerus** [comment] 2024-04-20 21:53
> That would be helpful. Thank you. My accounts don't have this issue so it's not possible to determine on my side.

This time I checked on version 19.11.38

"Append time stamps information" causes a loop on dev.10, without it **no loop** with all other default patches (I didn't check disabled patches like "Spoof player parameters", but I think they'll be ok)

>without it **no loop** with all other default patches

Except again for a small loop in the first Short, but the hell with it. It's still better than what was happening before

>a small loop in the first Short

That unfortunate "Downloads" item still plays a part in this. If it's not in the settings, everything works fine, there's no looping. (not shown in the video)

https://github.com/anddea/revanced-patches/assets/166645857/47526540-7bb4-40fc-a657-03df9ee85dad

Checked dev.9 again just in case, excluding all patches except the right ones. The loops were there

Of course I can also knock on the window of the original ReVanced and tell them: "Guys, you've got a little loop in the first Short," but unlike the loops we had before, this is a very minor problem. If anyone would want to report it, it wouldn't be me 🤠

>My accounts don't have this issue so it's not possible to determine on my side

In the comments above I offered you to use my account, but apparently the translator mistranslated the meaning of the text (or you didn't want to)

>I offered you to use my account

I can give you **my account login and password**. Since the error appeared on the devices that didn't have them originally, it is possible that it will appear on your devices as well

Or we can continue the correspondence in the comments x)
(but it's already a bit tiresome for me, after all, these checks, as well as recording videos, take me a lot of time)

**Comment by anddea** [comment] 2024-04-21 07:54
I was thinking about append timestamp info too, either that or RYD, thank you for your testing. What if you include patch but disable it in settings (Extended > Seekbar > Append timestamp info)? 

As a security researcher in my other time I propogate zero-trust apps and systems, that's why I don't ask for accounts even if you trust me. 

You could contact me on 4PDA as well (merluani).

**Comment by Zonkerus** [comment] 2024-04-21 11:18
> I was thinking about append timestamp info too, either that or RYD, thank you for your testing. What if you include patch but disable it in settings (Extended > Seekbar > Append timestamp info)?

Checked, disabling it in the settings doesn't help. Only exclusion from the build removes the loops

>You could contact me on 4PDA as well (merluani).

Okay, I'll text you

**Comment by Zonkerus** [comment] 2024-04-21 16:02
> That would be helpful. Thank you. My accounts don't have this issue so it's not possible to determine on my side.

This time I checked on version 19.11.38

"Append time stamps information" causes a loop on dev.10, without it **no loop** with all other default patches (I didn't check disabled patches like "Spoof player parameters", but I think they'll be ok)

>without it **no loop** with all other default patches

Except again for a small loop in the first Short, but the hell with it. It's still better than what was happening before

>a small loop in the first Short

That unfortunate "Downloads" item still plays a part in this. If it's not in the settings, everything works fine, there's no small looping. (not shown in the video)

https://github.com/anddea/revanced-patches/assets/166645857/47526540-7bb4-40fc-a657-03df9ee85dad

P.S: Checked dev.9 again just in case, excluding all patches except the right ones. The loops were there

**Comment by Quasar-0330** [comment] 2024-04-23 06:56
dev-12 fixed the problem perfectly in my environment (19.11.38, root)

**Closed** 2024-04-23 18:31 UTC
Labels: Bug report

**Comment by anddea** [comment] 2024-04-28 10:18
I reverted back temporary the fix as it caused crashes for some people. Until I find a better solution.

**Comment by Francesco146** [comment] 2024-05-09 22:54
i'm having the same issue, deleting the app data fixes it, but when i import my settings it starts again.

so i tried enabling the settings one by one, the b*stard one is:

`Default video quality on * network`

i had set it to `1080p` and it was giving problems, now I put it on `Auto` and I no longer have that stuttering. maybe we can take a look at this, and reopen this issue
