### ISSUE TITLE
bug: `Hide open mix playlist button`, `Hide open playlist button` & `Hide Related videos in quick actions` are broken

### ISSUE THREAD

**Issue by Rairof** [anddea/revanced-patches#421] opened 2024-05-03 19:43 UTC
### Type

Error at runtime

### Tools used

RVX Manager

### Application

YouTube v19.16.38

### Bug description

Relevant patches like `Hide open mix playlist button`, `Hide open playlist button` & `Hide Related videos in quick actions` dosen't work as these patch elements are still hidden even when they're toggled off along with video top title being hidden for no reason.
![Screenshot_20240504-052814](https://github.com/anddea/revanced-patches/assets/107706560/7a4c3081-949c-4771-9000-e6e361e95b35)
![Screenshot_20240504-053138](https://github.com/anddea/revanced-patches/assets/107706560/1e023aa0-0452-4e2e-af04-e118bcca174a)

### Error logs

```shell
N/A
```

### Solution

Fix relevant issues/patches

### Additional context

It was working fine until I updated from v2.225-dev 3 to latest patches

### Device Environment

Android 14, Project Elixir 4.1

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment] 2024-05-03 19:56
Can't reproduce this issue, working fine for me. Latest patches, latest supported YT.

**Comment by Rairof** [comment] 2024-05-03 20:21
https://github.com/anddea/revanced-patches/issues/421#issuecomment-2093676761
Want me to share settings file?

**Comment by anddea** [comment] 2024-05-03 20:49
Share your settings, let me see.

**Comment by Rairof** [comment] 2024-05-03 20:54
https://github.com/anddea/revanced-patches/issues/421#issuecomment-2093743693
Okay here it is.
[YouTube_v19.11.38_2024-04-18.txt](https://github.com/anddea/revanced-patches/files/15204984/YouTube_v19.11.38_2024-04-18.txt)

**Comment by Rairof** [comment] 2024-05-03 21:14
@anddea 

https://github.com/anddea/revanced-patches/assets/107706560/682b2d9f-2485-4884-bae5-cbb24a86e350

**Comment by anddea** [comment] 2024-05-04 08:03
I imported your settings and it shows only related videos in fullscreen quick actions, just like it's set in settings. To be just, I even repatched with RVX Manager and clean installed YT, same results. Not sure why it would happen to you, my first guess is (maybe) clear the Manager, clear temporary files in Manager settings.

**Comment by Rairof** [comment] 2024-05-04 09:27
https://github.com/anddea/revanced-patches/issues/421#issuecomment-2094071121
Just did a clean installation again with reinstalling RVX manager and the issues still exists

**Comment by anddea** [comment] 2024-05-04 10:26
Did you clear temporary files in the Manager? Reinstalling should've deleted them but sometimes it can leave trails. 

There should be no changes between dev 3 and dev 6 related to this issue. Try default settings and default patches and let me know if it's the same?

**Comment by Rairof** [comment] 2024-05-04 10:29
https://github.com/anddea/revanced-patches/issues/421#issuecomment-2094110709
Alright give me few minutes

**Comment by Francesco146** [comment] 2024-05-04 16:56
what manager are you using? if it doesn't work with that, try a clean install of [revancify](https://github.com/decipher3114/Revancify)

**Comment by Rairof** [comment] 2024-05-04 18:33
https://github.com/anddea/revanced-patches/issues/421#issuecomment-2094300963
I have been using RVX manager for quite a while now and had no issues with it

**Comment by anddea** [comment] 2024-05-07 09:46
RVX Manager should work fine, it works as expected for me. And I can't reproduce this issue, therefore I cannot fix.

**Comment by Rairof** [comment] 2024-05-07 18:12
https://github.com/anddea/revanced-patches/issues/421#issuecomment-2097893787
Maybe this is caused by my custom rom?
I'll check on other phones and reply back my results here.

**Comment by anddea** [comment] 2024-05-07 19:15
I doubt that your ROM is the reason. You said it worked before on your device.

**Comment by Rairof** [comment] 2024-05-07 19:43
https://github.com/anddea/revanced-patches/issues/421#issuecomment-2099130805
Then I don't know what's the issue, is there any way I can log this and share a log file?

**Comment by anddea** [comment] 2024-05-07 20:21
You can enable logging in Misc and capture it with logcat while using YT. Logs can contain some personal information. Let me know if it works on your other device. Did you test latest release with latest Manager, is it the same?

**Comment by Rairof** [comment] 2024-05-07 20:35
https://github.com/anddea/revanced-patches/issues/421#issuecomment-2099237880
I'll be getting the logs tomorrow.
It isn't working on other devices too, same issue on freshly installed YouTube no matter the device. Could it be due to some weird A/B test? I didn't tested with latest release 2.225-dev9 with latest manager but I still get this issue

**Comment by anddea** [comment] 2024-05-07 21:00
If you patched on one device and just copied to another it's expected that it will have the same issue. If it's A/B then this issue should't be on the new channel (even if it is on the same account), you can create it and test it. But I still get the impression that it should be something with a patching tool.

**Comment by Rairof** [comment] 2024-05-07 21:02
https://github.com/anddea/revanced-patches/issues/421#issuecomment-2099302650
I installed latest rvx manager into the other device and using same google account or different account didn't mattered.

**Comment by Rairof** [comment] 2024-05-08 03:05
Just now when watching video and switching between pip and Fullscreen view, it seems to fix these issues...Not sure why this happened.
![Screenshot_20240508-130404](https://github.com/anddea/revanced-patches/assets/107706560/83a0fabc-b2ad-4f07-b53d-9ea989e19263)

**Comment by anddea** [comment] 2024-05-08 06:06
I don't know as well, it never happened to me or anyone I asked about this issue. 

I'm gonna close it now but feel free to provide more information if you can find steps to reproduce it.

**Closed by anddea** 2024-05-08 06:06 UTC
Labels: Bug report
