### ISSUE TITLE
bug: (YouTube - Return YouTube Dislike): Live likes/views counts is sometimes shown wrong

### ISSUE THREAD

**Issue by imvoldemort** [anddea/revanced-patches#88] opened 2024-03-19 10:13 UTC
### Type

Cosmetic

### Tools used

RVX Manager

### Application

YouTube v19.09.37

### Bug description

Live likes/views counts displays very wierdly

### Device Environment

![304399080-73a7a725-5bd0-4014-8958-a4b622a1abef](https://github.com/anddea/revanced-patches/assets/159900453/c59d2646-1ded-4f5d-b993-8868f8b4c326)
![304399053-528ee506-2bb6-42ec-bd1c-963a5f9e6ceb](https://github.com/anddea/revanced-patches/assets/159900453/81874ff6-5ea0-4ba7-8535-c32f43b1b701)

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment] 2024-03-27 21:42
Is there any steps to reproduce? Because I couldn't reproduce it.

**Comment by imvoldemort** [comment] 2024-03-27 22:29
It happens everytime when the live count refreshes with or without incognito mode on.
Note - It doesn't happen on my second account.

**Comment by anddea** [comment] 2024-03-29 19:25
Second account but same device? Or other device?

**Comment by imvoldemort** [comment] 2024-03-30 09:19
Same device.

**Comment by Francesco146** [comment] 2024-05-02 20:44
i can reproduce the issue, although it's very random and unpredictable. I've no clue of this, not sure if even logs could explain this

**Comment by Francesco146** [comment] 2024-05-10 11:52
should be fixed in RVX

**Closed** 2024-05-10 15:42 UTC
Labels: Bug report
