### ISSUE TITLE
bug: Buffering 

### ISSUE THREAD

**Issue by Dimedro11** [anddea/revanced-patches#451] opened 2024-05-12 22:20 UTC
### Type

Other

### Tools used

Revancify

### Application

YouTube 19.16.38 dev 10

### Bug description

In the previous version, this error did not occur, but with the advent of the latest version, skipping buffering works so poorly that it works from the fourth or even the fifth time, and then after buffering it can switch from high quality to low quality.

### Solution

Implement buffer skipping operation as in the previous version of the build.

### Device Environment

Android 14
One ui 6.1

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment] 2024-05-12 22:41
Any video record? Don't have problems with buffering on my side.

**Comment by Dimedro11** [comment] 2024-05-12 22:58
> Есть видеозапись? У меня нет проблем с буферизацией.

https://drive.google.com/file/d/1--kHQERTk4dYLHA372cKGXdJRgehUqIW/view?usp=drivesdk

**Comment by anddea** [comment] 2024-05-15 07:48
I cannot access the link, you can attach screen record here in conversation. But if you have buffering issues then probably this A/B test reached you as well. You can repatch with older patches version, but probably you will face the same issue from now on, until the fix is found.

**Comment by OctavXD** [comment] 2024-05-15 10:27
Ymusic is mainly for music, but it also has an option to play videos. Maybe try to get in contact with ymusic developers since their app has no buffering issues

**Comment by Dimedro11** [comment] 2024-05-16 15:42
https://github.com/anddea/revanced-patches/assets/111146046/a84dfaaa-208f-4dfc-a919-0a0057d158fd

**Comment by anddea** [comment] 2024-05-16 16:03
I understand now. Can you reproduce it on inotia and ReVanced patches? The method for skipping preload buffer has changed a little bit during refactoring. If you face this issue on inotia patches open this issue in his repo.

**Comment by Dimedro11** [comment] 2024-05-16 18:45
Now I've tried to build a client with patches from inotia and I've built yours with extreme patches. It has become much better, that is, skipping buffering itself is going better. I can't say exactly what influenced the skipping of buffering, but the fact that it got better.

**Comment by anddea** [comment] 2024-05-16 19:11
It could be due to some unknown cached junk, sometimes when you clean install, it works much better. Although, I never faced anything like that even with updating on top but I use CLI. 

If it's fixed for you, close this issue.

**Closed** 2024-05-16 21:38 UTC
Labels: Bug report
